version: "3"
services:
  test_suite:
    image: sid0701/docker2024
    environment:
      - HUB_HOST=hub
      - BROWSER
      - THREAD_COUNT=1
      - TEST_SUITE
    volumes:
      - ./results/test_suite_results:/home/mydocker/test-output