version: "3"
services:
  vendor_portal_test:
    image: sid0701/docker2024
    environment:
      - HUB_HOST=hub
      - BROWSER
      - THREAD_COUNT=1
      - TEST_SUITE
    volumes:
      - ./results/test-suite:/home/mydocker/test-output